"""MCP server package — facade re-exporting symbols from `_legacy`.

This shim exists during the in-progress mcp_server.py split. The real
implementation lives in `_legacy.py`; subsequent commits carve it into
`bootstrap.py`, `app.py`, `runserver.py`, and `tools/*.py`. Until that
lands, every external caller (tests, route registrations, the CLI
entry point) keeps reaching the same names at the same paths.
"""

from journal.mcp_server._legacy import (
    ChromaVectorStore,
    Context,
    EntityExtractionService,
    FastMCP,
    IngestionService,
    JobRunner,
    QueryService,
    SQLiteEntityStore,
    SQLiteJobRepository,
    TransportSecuritySettings,
    _get_entity_extraction,
    _get_entity_store,
    _get_ingestion,
    _get_job_repository,
    _get_job_runner,
    _get_query,
    _init_services,
    _job_to_tool_dict,
    _poll_job_until_terminal,
    _services,
    _user_id,
    journal_backfill_mood_scores_batch,
    journal_extract_entities,
    journal_extract_entities_batch,
    journal_get_entity_mentions,
    journal_get_entity_relationships,
    journal_get_entries_by_date,
    journal_get_job_status,
    journal_get_mood_trends,
    journal_get_statistics,
    journal_get_topic_frequency,
    journal_ingest_media,
    journal_ingest_media_from_url,
    journal_ingest_multi_page,
    journal_ingest_multi_page_from_url,
    journal_ingest_text,
    journal_list_entities,
    journal_list_entries,
    journal_search_entries,
    journal_update_entry_text,
    lifespan,
    load_config,
    log,
    main,
    mcp,
)

__all__ = [
    "ChromaVectorStore",
    "Context",
    "EntityExtractionService",
    "FastMCP",
    "IngestionService",
    "JobRunner",
    "QueryService",
    "SQLiteEntityStore",
    "SQLiteJobRepository",
    "TransportSecuritySettings",
    "_get_entity_extraction",
    "_get_entity_store",
    "_get_ingestion",
    "_get_job_repository",
    "_get_job_runner",
    "_get_query",
    "_init_services",
    "_job_to_tool_dict",
    "_poll_job_until_terminal",
    "_services",
    "_user_id",
    "journal_backfill_mood_scores_batch",
    "journal_extract_entities",
    "journal_extract_entities_batch",
    "journal_get_entity_mentions",
    "journal_get_entity_relationships",
    "journal_get_entries_by_date",
    "journal_get_job_status",
    "journal_get_mood_trends",
    "journal_get_statistics",
    "journal_get_topic_frequency",
    "journal_ingest_media",
    "journal_ingest_media_from_url",
    "journal_ingest_multi_page",
    "journal_ingest_multi_page_from_url",
    "journal_ingest_text",
    "journal_list_entities",
    "journal_list_entries",
    "journal_search_entries",
    "journal_update_entry_text",
    "lifespan",
    "load_config",
    "log",
    "main",
    "mcp",
]
